### ISSUE TITLE
Doesn't retain texture of spriteshape

### ISSUE THREAD

**Issue by cjsillito** [Unity-Technologies/ReproProjectWizard#3] opened 2021-07-08 03:27 UTC
I tried using this on a scene with SpriteShapes but the main textures being used by the SpriteShapes were stripped out, so they couldn't be seen.  I even tried manually adding the prefab that used the SpriteShape, but still no texture.

**Comment by kindredkara** [comment] 2023-02-13 15:33
Hello! 
Repro Project Wizard has been completely updated and released as an experimental package within unity. Within this new version, our testing has found no issues with spriteshape's, so it should all work as intended!

The new version can be installed via the Package Manager using the name 'com.unity.repro-project-wizard'

https://docs.unity3d.com/Packages/com.unity.repro-project-wizard@0.2

**Closed as completed by kindredkara** 2023-02-13 15:33 UTC
